export { roleResource } from './role';
export { teacher2lessonResource } from './teacher2lesson';
export { userResource } from './User';
export { studentResource } from './Student';
export { groupResource } from './Group';
export { markResource } from './Mark';
export { scheduleResource } from './Schedule';
export { teacherResource } from './Teacher';
export { lessonResource } from './Lesson';
export { auditoryResource } from './Auditory';
export { specialtyResource } from './Specialty';
export { kafedraResource } from './Kafedra';
// export { orderResource } from './Order';
